/**
 * A React component to view a PDF document
 *
 * @see https://react-pdf-viewer.dev
 * @license https://react-pdf-viewer.dev/license
 * @copyright 2019-2024 Nguyen Huu Phuoc <me@phuoc.ng>
 */

'use client';

import * as React from 'react';
import { type PdfJsApiProvider } from './types/PdfJsApiProvider';
import { PdfJsApiContext } from './vendors/PdfJsApiContext';

const STYLE_ID = '___rpv-styles___';

export const Provider: React.FC<{
    children?: React.ReactNode;
    pdfApiProvider: PdfJsApiProvider;
    workerUrl: string;
}> = ({ children, pdfApiProvider, workerUrl }) => {
    pdfApiProvider.GlobalWorkerOptions.workerSrc = workerUrl;

    React.useInsertionEffect(() => {
        let styleEle = document.head.querySelector(`style[id=${STYLE_ID}]`);
        if (!styleEle) {
            styleEle = document.createElement('style');
            styleEle.setAttribute('id', STYLE_ID);
            document.head.appendChild(styleEle);

            // Override the styles of hidden canvas element generated by pdf-js
            styleEle.textContent = `
.hiddenCanvasElement {
    display: none;
    opacity: 0;
}`;
        }

        return () => {
            document.head.removeChild(styleEle);
        };
    }, []);

    return <PdfJsApiContext.Provider value={{ pdfJsApiProvider: pdfApiProvider }}>{children}</PdfJsApiContext.Provider>;
};
